#!/usr/bin/env python3
# _*_ coding: utf-8 _*_
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

x = np.linspace(-5,5, 20)

y1 = 3*x + 5
y2 = 15*x  + 10
y3 = 5/2*x - 1


plt.plot(x, y1, color='red')
plt.plot(x, y2, color='blue')
plt.plot(x, y3, color='orange')
plt.xlim(-5,5)
plt.ylim(-10,10)
plt.axhline(y=0, color='gray')
plt.axvline(x=0, color='gray')
